### ISSUE TITLE
"No results." on init?

### ISSUE THREAD

**Issue by mhkeller** [mokkabonna/inquirer-autocomplete-prompt#12]
When I launch the example it displays "No results..." as opposed to showing me the list as it used to do. It works as expected in https://github.com/mokkabonna/inquirer-autocomplete-prompt/commit/e75ae50681cecfd2ba8c23f804f61f6abf26c663 but breaks as of https://github.com/mokkabonna/inquirer-autocomplete-prompt/commit/faf4a4c17ae8153e7b5ec6b10b525b9343d0651a. I tried looking through there to see what might have caused it but didn't see it right away.

**Comment by mokkabonna** [comment]
It is because of this I guess https://github.com/mokkabonna/inquirer-autocomplete-prompt/compare/e75ae50681cecfd2ba8c23f804f61f6abf26c663...faf4a4c17ae8153e7b5ec6b10b525b9343d0651a#diff-168726dbe96b3ce427e7fedce31bb0bcR66

Moving from **undefined** to **null** as first input. Shouldn't be a problem in real world usage though. It is just that the example use a simple matching logic and it seems that  new RegExp behaves differently for the two values.

```js
new RegExp(undefined, 'i')
//=> /(?:)/i
new RegExp(null, 'i')
//=> /null/i
```

**Comment by mhkeller** [comment]
I see. Maybe adding `if (!input) return true` to the example would make it nicer for folks to get up and running.
